# Generated by Django 2.2 on 2021-10-16 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='questions',
        ),
    ]
