# Generated by Django 2.2 on 2021-10-16 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='score',
        ),
    ]
