# Generated by Django 2.2 on 2021-10-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='scores',
            field=models.IntegerField(),
        ),
    ]
